import Link from "next/link";

import { abmResourceImagePath } from "@/lib/abm/resource-links";
import { CellLibraryShell, SectionTitle, SmallCard } from "../../_cellLibraryShared";

export default function NeurologicalCellsPage() {
  return <CellLibraryShell title="Neurological" active="stem-cell-derived-cells" subActive="neurological">
    <section className="overflow-hidden rounded-[22px] border border-[#eadfd9] bg-white">
      <div className="grid gap-0 lg:grid-cols-[1.05fr_.95fr]">
        <div className="p-7 md:p-8"><div className="text-[11px] font-bold uppercase tracking-[0.12em] text-[#f15a29]">What Are NSC-Derived Cells?</div><h1 className="mt-2 text-[32px] font-semibold tracking-[-0.035em] text-[#414b55]">Neural stem cell-derived cells: a more reliable CNS model</h1><p className="mt-4 text-[13px] leading-6 text-neutral-700">Neural stem cells are self-renewing, multipotent CNS progenitors capable of generating neurons, astrocytes, and oligodendrocytes. Under controlled differentiation, they provide scalable cell models with consistent phenotype, validated markers, and functional behaviour.</p><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full border border-[#edd8cf] bg-[#fff7f2] px-3 py-1.5 text-[11px] font-semibold text-[#f15a29]">Controlled Source</span><span className="rounded-full border border-[#edd8cf] bg-[#fff7f2] px-3 py-1.5 text-[11px] font-semibold text-[#f15a29]">Physiological Relevance</span></div></div>
        <div className="min-h-[300px] bg-neutral-50"><img src={abmResourceImagePath("https://www.abmgood.com/assets/images/tinymce/nsc-derived-cells.png")} alt="NSC-derived neuronal cells" className="h-full w-full object-cover" /></div>
      </div>
    </section>

    <section className="mt-6 rounded-[22px] border border-[#eadfd9] bg-[#fffaf7] p-7"><SectionTitle eyebrow="Why NSC-derived cells" title="What makes them different?" text="A banked, characterized progenitor source reduces dependence on repeated primary tissue isolation while retaining a CNS-relevant phenotype." /><div className="mt-5 grid gap-4 md:grid-cols-3"><SmallCard index="1" title="Renewable Supply" text="Banked progenitor cells support scalable studies without repeated primary tissue isolation." /><SmallCard index="2" title="Reduced Variability" text="Defined differentiation and a controlled source improve consistency across experiments." /><SmallCard index="3" title="Flexible CNS Assays" text="Models support 2D culture, neuron–glia co-culture, 3D integration, imaging, transcriptomics, and electrophysiology." /></div></section>

    <section className="mt-6 rounded-[22px] border border-[#eadfd9] bg-white p-7"><SectionTitle eyebrow="Research applications" title="What can you model with neuronal cells?" text="NSC-derived neuronal and glial cells support CNS workflows that depend on a consistent phenotype and scalable supply." /><div className="mt-5 overflow-hidden rounded-[16px] border border-neutral-200 bg-[#fafafa] p-3"><img src={abmResourceImagePath("https://www.abmgood.com/assets/images/tinymce/mFZMmfjHh62xDaN7B65UOW3iZ1NVmVoL2hknKQgd.png")} alt="Applications of NSC-derived neuronal cells" className="mx-auto h-auto max-h-[520px] w-full object-contain" /></div></section>

    <section className="mt-6 rounded-[22px] border border-[#eadfd9] bg-[#fffaf7] p-7"><SectionTitle eyebrow="Our Collection" title="NSC-derived neuronal cells" text="The current collection contains cryopreserved neural-stem-cell-derived neuronal and glial models with matched culture support." /><div className="mt-5 grid gap-5 md:grid-cols-2"><article className="rounded-[18px] border border-[#eadfd9] bg-white p-5"><div className="text-[11px] font-bold uppercase tracking-[0.1em] text-[#f15a29]">T5001 · Rat</div><h3 className="mt-2 text-xl font-semibold text-[#414b55]">Rat Neurons</h3><p className="mt-3 text-[12px] leading-5 text-neutral-600">Differentiated neuronal cells derived from rat neural stem cells. Post-thaw cultures form functional networks and express neuronal marker MAP2.</p><dl className="mt-4 grid grid-cols-[100px_1fr] gap-y-2 text-[12px]"><dt className="font-semibold">Cat. No.</dt><dd>T5001</dd><dt className="font-semibold">Unit</dt><dd>2×10⁶ cells / 1.0 mL</dd><dt className="font-semibold">Format</dt><dd>Frozen</dd><dt className="font-semibold">Key marker</dt><dd>MAP2⁺</dd></dl><Link href="/products/abm/staged/product/T5001" className="mt-5 inline-flex text-[12px] font-semibold text-[#f15a29]">View product page →</Link></article><article className="rounded-[18px] border border-[#eadfd9] bg-white p-5"><div className="text-[11px] font-bold uppercase tracking-[0.1em] text-[#f15a29]">T5005 · Rat</div><h3 className="mt-2 text-xl font-semibold text-[#414b55]">Rat Astrocytes</h3><p className="mt-3 text-[12px] leading-5 text-neutral-600">NSC-derived astrocytes with stellate morphology and GFAP expression for monoculture, co-culture, and 3D systems.</p><dl className="mt-4 grid grid-cols-[100px_1fr] gap-y-2 text-[12px]"><dt className="font-semibold">Cat. No.</dt><dd>T5005</dd><dt className="font-semibold">Unit</dt><dd>1×10⁶ cells / 1.0 mL</dd><dt className="font-semibold">Format</dt><dd>Frozen</dd><dt className="font-semibold">Key marker</dt><dd>GFAP⁺</dd></dl><Link href="/products/abm/staged/product/T5005" className="mt-5 inline-flex text-[12px] font-semibold text-[#f15a29]">View product page →</Link></article></div><p className="mt-4 text-[12px] italic text-neutral-500">Coming soon: Human NSC-derived neuronal models for donor- and disease-relevant CNS research.</p></section>

    <section className="mt-6 rounded-[22px] border border-[#eadfd9] bg-white p-7"><SectionTitle eyebrow="Culture System" title="Validated media & surface coating system" text="Matched media and surface reagents support reliable post-thaw recovery, morphology, and functional maturation." /><div className="mt-5 grid gap-4 md:grid-cols-2"><SmallCard title="TM208 · iNeuraDiffX™ Medium Kit" text="Differentiation and maintenance medium for rat neurons, supporting maturation and network formation." /><SmallCard title="TM207 · iNeuraGroXpan™ Medium Kit" text="Neural stem cell expansion medium for thaw and propagation workflows." /><SmallCard title="TM062 · PLO + Laminin Coating" text="Surface coating supports neuronal adhesion and neurite extension." /><SmallCard title="TM078 · CryoGuard™" text="Serum-free cryopreservation medium designed to reduce freeze–thaw damage." /></div></section>

    <section className="mt-6 rounded-[22px] border border-[#eadfd9] bg-[#fffaf7] p-7"><SectionTitle eyebrow="FAQ" title="Frequently Asked Questions" /><div className="mt-5 space-y-3"><SmallCard title="How do NSC-derived neurons differ from primary neurons?" text="They are produced from a controlled banked progenitor source, reducing lot variability and avoiding fresh tissue isolation for every experiment." /><SmallCard title="What culture support is required?" text="Neuronal models use defined media and appropriate PLO/Laminin surface coating; requirements vary by selected cell type." /></div></section>
  </CellLibraryShell>;
}
