import Link from "next/link";

import { CellLibraryShell } from "../../_cellLibraryShared";

export default function NkCellsPage() {
  return <CellLibraryShell title="NK Cells" active="hematopoietic-cells" subActive="nk-cells">
    <section className="border-b border-neutral-200 pb-8"><h1 className="text-[29px] font-semibold tracking-[-0.025em] text-[#414b55]">NK Cells</h1><h2 className="mt-3 text-[21px] font-semibold text-[#414b55]">Highly Purified. Cytotoxic. Research-Ready.</h2><p className="mt-4 max-w-4xl text-[13px] leading-6 text-neutral-700">Primary human NK cells (CD3⁻CD56⁺) are isolated from healthy-donor peripheral blood and provided fresh or cryopreserved for immunology, cell-therapy development, and high-throughput screening.</p><div className="mt-5 rounded-[4px] bg-[#fafafa] p-5 text-[13px] leading-6"><div className="font-bold">Key Features</div><ul className="mt-2 list-disc pl-5"><li>Purity: &gt;90% CD3⁻CD56⁺ population by FACS</li><li>Viability: &gt;95% post-thaw</li></ul></div><p className="mt-5 max-w-4xl text-[13px] leading-6 text-neutral-700">PrimGrow NK-Xpan™ is a chemically defined, serum-free medium for selective NK-cell expansion, activation, and maintenance while supporting cytolytic function.</p><ul className="mt-3 list-disc space-y-2 pl-5 text-[13px] leading-5 text-neutral-700"><li>Serum-free and xeno-free</li><li>Supports expansion with minimal T-cell contamination</li><li>Pre-supplemented with IL-2 and IL-15</li><li>Compatible with feeder-free and feeder-based protocols</li></ul></section>
    <section className="mt-7"><h2 className="text-[22px] font-semibold text-[#414b55]">Product List</h2><div className="mt-4 overflow-hidden rounded-md border border-neutral-200"><table className="w-full text-left text-[13px]"><thead><tr className="bg-neutral-50"><th className="px-4 py-3">Product Name</th><th className="px-4 py-3">Cat. No.</th><th className="px-4 py-3">Unit</th></tr></thead><tbody>{[["T-NK Cells","T4167","1×10⁶ Cells"],["PrimGrow NK Xpan™ Medium Kit","TM183","500 ml"]].map(([name,sku,unit]) => <tr key={sku} className="border-t border-neutral-200"><td className="px-4 py-3"><Link href={`/products/abm/staged/product/${sku}`} className="font-semibold text-[#d95628]">{name}</Link></td><td className="px-4 py-3">{sku}</td><td className="px-4 py-3">{unit}</td></tr>)}</tbody></table></div></section>
  </CellLibraryShell>;
}
