import type { KentOfficialProductOverride } from "./official-product-overrides";

const SOMNOSUITE: KentOfficialProductOverride = {
  title: "SomnoSuite®",
  summary: "Low-flow anesthesia system",
  sku: "SS-01",
  leadHtml:
    "<p>SomnoSuite® is Kent Scientific’s innovative low-flow anesthesia delivery system designed specifically for mice and rats. Unlike traditional vaporizers, the SomnoSuite is engineered with a precision syringe pump and integrated digital vaporizer which uses either room air or compressed gas to deliver anesthesia at low flow rates proportionate to the animal’s size.</p><p>Using less anesthesia not only benefits the animal during procedures, but significantly reduces the risk of exposure to lab personnel from waste anesthesia gas.</p><p><strong>Every SomnoSuite ships with RightTemp®.</strong></p>",
  sections: [
    {
      _key: "somnosuite-related",
      type: "related-products",
      title: "Customers who viewed this item also viewed",
      items: [
        {
          _key: "somnosuite-related-surgisuite-rat",
          title: "SurgiSuite – For Rats",
          href: "/products/kent/item/surgisuite",
        },
        {
          _key: "somnosuite-related-surgisuite-mouse",
          title: "SurgiSuite – For Mice",
          href: "/products/kent/item/surgisuite",
        },
        {
          _key: "somnosuite-related-masks",
          title: "Anesthesia Masks/Breathing Circuits for SomnoSuite®",
          href: "/products/kent/item/anesthesia-masks-breathing-circuits-for-somnosuite",
        },
      ],
    },
    {
      _key: "somnosuite-features",
      type: "features",
      title: "What you get with SomnoSuite",
      items: [
        { _key: "somnosuite-feature-flow", title: "Flow Rates from 25 mL to 1 L", description: "Uses less than 1 mL of isoflurane per hour with typical use." },
        { _key: "somnosuite-feature-calibration", title: "No Servicing or Calibration Needed", description: "Active vaporization technology does not require annual calibration and includes a no-calibration certificate for facility inspections." },
        { _key: "somnosuite-feature-vaporizer", title: "Integrated digital vaporizer", description: "Automatically calculates flow rate based on animal weight." },
        { _key: "somnosuite-feature-compressor", title: "Built-In Air Compressor", description: "Uses room air or compressed gas." },
        { _key: "somnosuite-feature-stereotaxic", title: "Easily Integrates Into Stereotaxic Setups", description: "Use your own anesthesia mask or a compatible Kent mask." },
        { _key: "somnosuite-feature-multi", title: "Multi-Animal Capability", description: "Supports efficient study workflows and protocol review for application suitability." },
        { _key: "somnosuite-feature-modular", title: "Modular Capability", description: "Supports integrated physiological monitoring modules for different applications." },
        { _key: "somnosuite-feature-recording", title: "Real-Time Recordings and Data Output Capabilities", description: "Compatible with third-party data acquisition software such as LabChart and Spike2." },
        { _key: "somnosuite-feature-flush", title: "Induction Chamber Flush", description: "Minimizes waste anesthetic gas exposure." },
        { _key: "somnosuite-feature-screen", title: "Intuitive Touch Screen Control", description: "The multi-parameter touch screen displays vital signs and system information." },
        { _key: "somnosuite-feature-guidelines", title: "Complies with Regulatory Guidelines", description: "Low-flow vaporization reduces anesthetic use, exposure and waste anesthetic gas." },
        { _key: "somnosuite-feature-footprint", title: "Smaller footprint", description: "Smaller than a traditional vaporizer and stand, with further space savings when modules are combined." },
        { _key: "somnosuite-feature-animal", title: "Safer for the Animal", description: "Digital control supports precise anesthetic delivery." },
        { _key: "somnosuite-feature-technician", title: "Safer for the technician", description: "Low anesthetic and carrier-gas use reduces waste-gas exposure risk." },
        { _key: "somnosuite-feature-alarms", title: "5 Safety Alarms" },
      ],
    },
    {
      _key: "somnosuite-reviews",
      type: "reviews",
      title: "What your peers say",
      items: [
        { _key: "somnosuite-review-dempsey", title: "Elizabeth Dempsey, Ph.D — Northwestern University", description: "I use a SomnoSuite/RightTemp system purchased from Kent in May of this year – it’s been awesome! Before that, I was renting a traditional isoflurane vaporizer system from our institution’s animal facility, and using a very bulky circulating water heating pad, so we’ve been very happy with the new unit." },
        { _key: "somnosuite-review-schlink", title: "Sarah Schlink, DVM, DACLAM — University of Missouri", description: "We have a few SomnoSuites as well as SomnoFlos, they are great!" },
        { _key: "somnosuite-review-chapa", title: "Jaedan Chapa — University of Texas Rio Grande Valley", description: "The SomnoSuite was vital for conducting research where two NIH-funded projects required anesthesia and ventilatory assistance. It provided a vital tool for both stereotaxic and cardiovascular surgery." },
        { _key: "somnosuite-review-hargis", title: "Julie Hargis, RVT — Cincinnati Children’s Hospital Medical Center", description: "We currently use the SomnoSuite and love it!" },
        { _key: "somnosuite-review-mcgrail", title: "Sean McGrail, Scientific Laboratory Manager — University of Florida", description: "We bought a SomnoSuite 10 months ago and we are loving it." },
        { _key: "somnosuite-review-blake", title: "Jessica Blake, MBA — University of California San Diego / VA San Diego Healthcare Systems", description: "I purchased three SomnoSuite tabletop anesthesia setups and we love them!" },
        { _key: "somnosuite-review-khan", title: "Dr. Wasif Afsari Khan, PhD — University of Texas Health Science Center", description: "The SomnoSuite allows us to lower the anesthesia level while recording neural signals with high signal-to-noise ratio. We also value its very low isoflurane waste and the ability to draw oxygen from room air without an extra oxygen setup." },
        { _key: "somnosuite-review-ciochina", title: "Raluca Ciochina, Research Program Coordinator — University of California San Diego", description: "We work well with the SomnoSuite system; it is very useful for our mouse surgeries." },
        { _key: "somnosuite-review-mourtada", title: "Rida Mourtada, PhD — Lycia Therapeutics", description: "We use the SomnoSuite for anesthesia in rats and mice while monitoring body temperature and have had a great experience." },
        { _key: "somnosuite-review-bakhshi", title: "Kayenat Bakhshi — Research Technician, University of Arizona", description: "SomnoSuite works great. We have two and both are fantastic." },
        { _key: "somnosuite-review-slivano", title: "Orazio Slivano, Histology Research Manager — Augusta University", description: "We purchased two SomnoSuite systems about six months ago. They work very well." },
        { _key: "somnosuite-review-jones", title: "Jeffrey A. Jones, PhD — Medical University of South Carolina / VA Research Service", description: "We enjoyed our original SomnoSuite so much that we ordered two more. They are relatively easy to set up and start." },
      ],
    },
    {
      _key: "somnosuite-resources",
      type: "documents",
      title: "SomnoSuite resources",
      items: [
        { _key: "somnosuite-resource-setup", label: "SomnoSuite® Setup", url: "https://youtu.be/DYf94hIpMO0" },
        { _key: "somnosuite-resource-calibration", label: "SomnoSuite® Requires No Calibration", url: "https://youtu.be/6odvj6TOvRI" },
        { _key: "somnosuite-resource-benefits", label: "SomnoSuite® Benefits", url: "https://youtu.be/ZgHDbvS8pWM" },
        { _key: "somnosuite-resource-air", label: "SomnoSuite® Ambient Air", url: "https://youtu.be/kA0Ldmu4hkI" },
        { _key: "somnosuite-resource-room-air", label: "Room Air v. 100% O₂: Considerations for Anesthetic Delivery", url: "https://youtu.be/084iNEIp5bY" },
      ],
    },
    {
      _key: "somnosuite-about",
      type: "rich-text",
      title: "About SomnoSuite",
      html: "<h3>Overview</h3><p>SomnoSuite is Kent Scientific’s innovative low-flow anesthesia delivery system designed specifically for mice and rats.</p><p>Unlike traditional vaporizers, the SomnoSuite is engineered with a precision syringe pump and integrated digital vaporizer which uses either room air or compressed gas to deliver anesthesia at low flow rates proportionate to the animal’s size.</p><p>Using less anesthesia not only benefits the animal during procedures, but significantly reduces the risk of exposure to lab personnel from waste anesthesia gas.</p><h3>Uses less anesthetic gas</h3><p>The SomnoSuite is specifically designed for mice and rats and is pre-calibrated for use with both isoflurane and sevoflurane. During a typical 30-minute procedure at 2.5% isoflurane, it uses less than 0.3 mL of isoflurane and can anesthetize up to two mice simultaneously. The internal pump allows operation with room air or an external compressed-gas source.</p><h3>Syringe selection</h3><p>For optimum precision, response and consistency, Kent recommends a 5 mL syringe for mice and a 10 mL syringe for rats. Because mice require very low maintenance flow rates, a smaller syringe keeps the syringe driver moving more consistently and reduces pulsatile anesthetic delivery.</p><p>For a 30 g animal at a calculated maintenance flow of 36 mL/min and 1.5% isoflurane, the syringe pump moves approximately four pulses per second with a 5 mL syringe and two pulses per second with a 10 mL syringe.</p>",
    },
    {
      _key: "somnosuite-included",
      type: "included",
      title: "Base system includes",
      items: [
        { _key: "somnosuite-included-display", title: "Integrated touch-screen display" },
        { _key: "somnosuite-included-memory", title: "Internal memory for data storage" },
        { _key: "somnosuite-included-usb", title: "Mini-USB for data output" },
        { _key: "somnosuite-included-adapter", title: "Anti-spill, anti-vapor bottle top adapter" },
        { _key: "somnosuite-included-accessory", title: "Two-accessory adapter" },
        { _key: "somnosuite-included-wag", title: "WAG canister and holder" },
        { _key: "somnosuite-included-warranty", title: "1-year parts and labor standard warranty" },
      ],
    },
    {
      _key: "somnosuite-addons",
      type: "addons",
      title: "Extend your SomnoSuite's capabilities with add-on modules",
      description: "Every SomnoSuite ships with RightTemp and can be configured with additional monitoring and ventilation modules.",
      items: [
        { _key: "somnosuite-addon-righttemp", title: "SomnoSuite with RightTemp®", description: "Temperature monitoring and homeothermic control. Set the desired core temperature and the system automatically controls the warming pad." },
        { _key: "somnosuite-addon-rovent", title: "RoVent®", description: "Advanced small-animal ventilator for mice, rats and guinea pigs up to 1,250 g, with volume or pressure control, integrated PEEP and automated sigh breaths." },
        { _key: "somnosuite-addon-mousestat", title: "MouseSTAT®", description: "Pulse oximeter and heart-rate monitor for small animals, with sensors designed for heart rates up to 900 bpm." },
        { _key: "somnosuite-addon-capnoscan", title: "CapnoScan®", description: "End-tidal CO₂ monitor with real-time capnography and sidestream sampling for intubated and ventilated animals." },
      ],
    },
    {
      _key: "somnosuite-publications",
      type: "publications",
      title: "Scientific publications",
      html: "<ul><li>Analysis of the distribution of vagal afferent projections from different peripheral organs to the nucleus of the solitary tract in rats</li><li>Chemogenetic emulation of intraneuronal oxidative stress affects synaptic plasticity</li><li>Cognitive and behavioral effects of whole brain conventional or high dose rate (FLASH) proton irradiation in a neonatal Sprague Dawley rat model</li><li>Conservation of locomotion-induced oculomotor activity through evolution in mammals</li><li>Development of the Periventricular Nucleus as a Brain Center, Containing Dopaminergic Neurons and Neurons Expressing Individual Enzymes of Dopamine Synthesis</li><li>Dissociation of spatial and object memory in the hippocampal formation of Japanese quail</li><li>Gaining insight into the neural basis of resting-state fMRI signal</li><li>Longitudinal in Utero Analysis of Engrailed-1 Knockout Mouse Embryonic Phenotypes Using High-Frequency Ultrasound</li><li>Molecular identification of bulbospinal ON neurons by GPER which drives pain and morphine tolerance</li><li>MRI-Guided Electrode Implantation for Chronic Intracerebral Recordings in a Rat Model of Post-Traumatic Epilepsy—Challenges and Gains</li></ul>",
    },
    {
      _key: "somnosuite-warranty",
      type: "warranty",
      title: "Warranty information",
      rows: [
        { Configuration: "SomnoSuite® with RightTemp®", Plan: "Standard", Coverage: "1 year", Benefits: "Controller coverage" },
        { Configuration: "SomnoSuite® with RightTemp®", Plan: "Extended", Coverage: "Additional 2 years", Benefits: "Extended controller coverage" },
        { Configuration: "SomnoSuite® with RightTemp®", Plan: "Premium", Coverage: "Additional 2 years", Benefits: "Loaner equipment, next-day loaner shipping, training and expedited repairs" },
        { Configuration: "SomnoSuite® with RightTemp® and MouseSTAT®", Plan: "Standard", Coverage: "1 year", Benefits: "Controller coverage" },
        { Configuration: "SomnoSuite® with RightTemp® and MouseSTAT®", Plan: "Extended", Coverage: "Additional 2 years", Benefits: "Extended controller coverage" },
        { Configuration: "SomnoSuite® with RightTemp® and MouseSTAT®", Plan: "Premium", Coverage: "Additional 2 years", Benefits: "Loaner equipment, next-day loaner shipping, training and expedited repairs" },
        { Configuration: "SomnoSuite® with RightTemp®, MouseSTAT® and RoVent®", Plan: "Standard", Coverage: "1 year", Benefits: "Controller coverage" },
        { Configuration: "SomnoSuite® with RightTemp®, MouseSTAT® and RoVent®", Plan: "Extended", Coverage: "Additional 2 years", Benefits: "Extended controller coverage" },
        { Configuration: "SomnoSuite® with RightTemp®, MouseSTAT® and RoVent®", Plan: "Premium", Coverage: "Additional 2 years", Benefits: "Loaner equipment, next-day loaner shipping, training and expedited repairs" },
      ],
    },
    {
      _key: "somnosuite-warranty-notes",
      type: "notice",
      title: "Warranty notes",
      html: "<ul><li>Damage or failures caused by abuse, negligence or misuse are not covered.</li><li>Expedited repair time begins after the product is received and ends when it is shipped to the customer.</li><li>The customer must identify the request as a warranty claim.</li><li>An extended warranty purchased after the original sale may require controller inspection and approval.</li></ul>",
    },
    {
      _key: "somnosuite-faqs",
      type: "faqs",
      title: "FAQs",
      html: "<h3>Are there limitations to using room air with the SomnoSuite?</h3><p>The SomnoSuite can be used for long procedures with room air. Physiological parameters should be monitored throughout the procedure, and supplemental oxygen or mechanical ventilation may be useful in some cases.</p><h3>Can I output data?</h3><p>The system includes one analog output for a single parameter and can export all parameters digitally through mini-USB.</p><h3>Is the SomnoSuite compatible with stereotaxic masks?</h3><p>Yes. It includes adapters that fit most stereotaxic gas-anesthesia masks.</p><h3>Do I need a pressure reducer to use compressed gas?</h3><p>The SomnoSuite requires a gas input of 5–10 psi. Use a suitable regulator or a pre-set pressure reducer when the source pressure is higher.</p><h3>What type of scavenging is recommended?</h3><p>Passive scavenging is sufficient. An F/AIR canister is included with each system.</p><h3>Does the unit connect to a gas supply?</h3><p>Yes. It can use room air or an external gas supply connected to the rear of the unit.</p><h3>How portable is the SomnoSuite?</h3><p>It is similar in size to a laptop computer. The internal pump permits ambient-air operation, and the battery supports field work or locations without a nearby outlet.</p><h3>What are the dimensions?</h3><ul><li>Length: 11.5 in (29.2 cm)</li><li>Width: 8.5 in (21.59 cm)</li><li>Height: 3 in (7.62 cm) top; 1.75 in (4.45 cm) bottom</li><li>Weight: 3.65 lb (1.6 kg)</li></ul><h3>What are the fittings and hose sizes?</h3><p>The fitting size is 1/4 in and the tubing is 1/4 in × 3/8 in PVC.</p><h3>Which syringe size should I use?</h3><p>Kent recommends the smallest syringe that accommodates the application duration. A smaller syringe generally provides more accurate and uniform delivery at low flow rates.</p>",
    },
  ],
};

export default SOMNOSUITE;
