import Link from "next/link";

import { CellLibraryShell } from "../../_cellLibraryShared";

export default function TCellsPage() {
  return <CellLibraryShell title="T Cells (CD4⁺, CD8⁺, Treg, γδ)" active="hematopoietic-cells" subActive="t-cells-cd4-cd8-treg">
    <section className="border-b border-neutral-200 pb-8"><h1 className="text-[29px] font-semibold tracking-[-0.025em] text-[#414b55]">T Cells (CD4⁺, CD8⁺, Treg, γδ)</h1><h2 className="mt-3 text-[21px] font-semibold text-[#414b55]">Purified, Functional, and Ready for Immune Innovation</h2><p className="mt-4 max-w-4xl text-[13px] leading-6 text-neutral-700">abm’s human T-cell subsets are isolated from PBMCs using immunomagnetic selection for high viability and subtype specificity. The collection supports T-cell signaling, CAR-T engineering, inflammation, tolerance, and immunomodulator screening.</p><div className="mt-5 rounded-[4px] bg-[#fafafa] p-5 text-[13px] leading-6"><div className="font-bold">Product Features</div><ul className="mt-2 list-disc pl-5"><li>CD4⁺ helper T cells</li><li>CD8⁺ cytotoxic T cells</li><li>CD4⁺CD25⁺ regulatory T cells</li><li>γδ T cells</li><li>Purity greater than 90% for all subsets by FACS validation</li></ul></div></section>
    <section className="mt-7"><h2 className="text-[22px] font-semibold text-[#414b55]">Product List</h2><div className="mt-4 overflow-hidden rounded-md border border-neutral-200"><table className="w-full text-left text-[13px]"><thead><tr className="bg-neutral-50"><th className="px-4 py-3">Product Name</th><th className="px-4 py-3">Cat. No.</th><th className="px-4 py-3">Unit</th></tr></thead><tbody>{[["T-CD4+ Cells","T4183","1×10⁷ Cells"],["T-CD8+ Cells","T4184","1×10⁷ Cells"],["Treg Cells","T4185","1×10⁶ Cells"],["Tγδ Cells","T4186","1×10⁶ Cells"]].map(([name,sku,unit]) => <tr key={sku} className="border-t border-neutral-200"><td className="px-4 py-3"><Link href={`/products/abm/staged/product/${sku}`} className="font-semibold text-[#d95628]">{name}</Link></td><td className="px-4 py-3">{sku}</td><td className="px-4 py-3">{unit}</td></tr>)}</tbody></table></div></section>
    <section className="mt-8 border-t border-neutral-200 pt-7"><h2 className="text-[24px] font-semibold text-[#414b55]">T Cell Culture Medium</h2><h3 className="mt-2 text-[18px] font-semibold text-[#414b55]">PrimGrow T-X™ – Optimized Expansion Medium for Human T Cells</h3><p className="mt-3 max-w-4xl text-[13px] leading-6 text-neutral-700">A serum-free, xeno-free formulation designed to support human T-cell expansion, phenotypic stability, and cytokine responsiveness across multiple T-cell subsets.</p><ul className="mt-4 list-disc space-y-2 pl-5 text-[13px] leading-5 text-neutral-700"><li>Ready-to-use, pre-supplemented formulation</li><li>Supports expansion and polarization workflows</li><li>Compatible with additional cytokines or anti-CD3/CD28 activation strategies</li></ul><div className="mt-5 border-y border-neutral-200 px-4 py-3 text-[13px]"><Link href="/products/abm/staged/product/TM182" className="font-semibold text-[#d95628]">PrimGrow T Xpan™ Medium Kit</Link> <span className="ml-4 text-neutral-600">TM182 · 500 ml</span></div></section>
  </CellLibraryShell>;
}
