import Link from "next/link";

import { abmResourceImagePath } from "@/lib/abm/resource-links";
import { CellLibraryShell, SectionTitle, SmallCard } from "../../_cellLibraryShared";

export default function CardiovascularCellsPage() {
  return <CellLibraryShell title="Cardiovascular" active="stem-cell-derived-cells" subActive="cardiovascular">
    <section className="overflow-hidden rounded-[22px] border border-[#eadfd9] bg-[#fffaf7]">
      <div className="grid gap-0 lg:grid-cols-[1.1fr_.9fr]">
        <div className="p-7 md:p-8"><div className="text-[11px] font-bold uppercase tracking-[0.12em] text-[#f15a29]">T5004 · Research Use Only</div><h1 className="mt-2 text-[36px] font-semibold tracking-[-0.04em] text-[#414b55]">Human Cardiomyocytes</h1><h2 className="mt-3 text-[22px] font-semibold leading-7 text-[#4b5560]">Stop Waiting. Start Beating.</h2><p className="mt-3 text-[14px] leading-6 text-neutral-700">Ready-to-use human embryonic stem cell-derived cardiomyocytes are cryopreserved and functionally validated, with spontaneous contractions typically beginning within 3–5 days after plating.</p><p className="mt-3 text-[13px] leading-6 text-neutral-600">T5004 provides a reproducible human cardiac model for drug discovery, cardiotoxicity screening, disease modelling, electrophysiology, and advanced 3D cardiac workflows.</p><div className="mt-5 flex flex-wrap gap-2"><Link href="#validation" className="rounded-full bg-[#f15a29] px-5 py-2.5 text-[12px] font-bold text-white">See Validation Data</Link><Link href="/products/abm/staged/product/T5004" className="rounded-full border border-[#f15a29] bg-white px-5 py-2.5 text-[12px] font-semibold text-[#f15a29]">View T5004 Product Page</Link></div></div>
        <div className="min-h-[280px] bg-neutral-100"><img src={abmResourceImagePath("https://www.abmgood.com/assets/images/tinymce/xxgRnSyY5IM6WENcISDTzEot1IlhWK5tIV1geBUO.png")} alt="Human cardiomyocytes" className="h-full w-full object-cover" /></div>
      </div>
    </section>

    <section className="mt-6 rounded-[22px] border border-[#eadfd9] bg-white p-7"><SectionTitle eyebrow="Functional recovery" title="Watch Human Cardiomyocytes Beat" text="Representative cultures demonstrate spontaneous contractions after plating, with beating typically observed within 3–5 days." /><div className="mt-5 aspect-video overflow-hidden rounded-[16px] border border-neutral-200 bg-black"><iframe src="https://www.youtube.com/embed/4tjoHVjmFpk?rel=0" title="Human embryonic stem cell-derived cardiomyocytes beating" className="h-full w-full" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /></div></section>

    <section className="mt-6 rounded-[22px] border border-[#eadfd9] bg-[#fffaf7] p-7"><SectionTitle eyebrow="Functional validation" title="Ready-to-use cardiac cells for time-sensitive workflows" /><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-5"><SmallCard title="Genetic Stability" text="Embryonic stem cell origin supports consistent cellular identity." /><SmallCard title="Rapid Recovery" text="Spontaneous beating typically begins within 3–5 days." /><SmallCard title="Cardiac Identity" text="Key contractility markers are characterized by molecular and imaging assays." /><SmallCard title="Consistency" text="Controlled differentiation supports repeatable experimental outcomes." /><SmallCard title="Performance" text="Functional cardiac behaviour is maintained for roughly 10–14 days in culture." /></div></section>

    <section className="mt-6 rounded-[22px] border border-[#eadfd9] bg-white p-7"><SectionTitle eyebrow="Applications" title="Human-relevant cardiac workflows" /><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><SmallCard title="Drug Discovery" text="Evaluate efficacy and cardiac responses during preclinical development." /><SmallCard title="Cardiotoxicity Screening" text="Identify adverse cardiac effects earlier during compound evaluation." /><SmallCard title="Disease Modelling" text="Study cardiac physiology and disease mechanisms in a human cell model." /><SmallCard title="Electrophysiology & Contractility" text="Assess beating behaviour, electrical activity, and functional response." /><SmallCard title="Tissue Engineering & Organoids" text="Build advanced 3D cardiac models and organoid systems." /></div></section>

    <section id="validation" className="mt-6 rounded-[22px] border border-[#eadfd9] bg-[#fffaf7] p-7"><SectionTitle eyebrow="Validation Data" title="Verified cardiac identity and function" text="T5004 undergoes molecular, phenotypic, and functional characterization to support cardiac lineage identity and performance." /><div className="mt-5 grid gap-5 md:grid-cols-2"><figure className="overflow-hidden rounded-[16px] border border-neutral-200 bg-white"><img src={abmResourceImagePath("https://www.abmgood.com/assets/images/tinymce/kLwASnPOZne6Gk7qWHqTifJsX7cf8hjZLdqqOnRa.png")} alt="RT-qPCR cardiomyocyte validation" className="h-auto w-full object-contain" /><figcaption className="p-4 text-[12px] font-semibold text-neutral-700">RT-PCR Validation · Expression Analysis</figcaption></figure><figure className="overflow-hidden rounded-[16px] border border-neutral-200 bg-white"><img src={abmResourceImagePath("https://www.abmgood.com/assets/images/tinymce/2pPQSIiKzaOOHhFr0hA5rly9rtqlLOjFIbtNTvuB.png")} alt="Cardiomyocyte immunocytochemistry validation" className="h-auto w-full object-contain" /><figcaption className="p-4 text-[12px] font-semibold text-neutral-700">Immunocytochemistry · Contractile Marker Expression</figcaption></figure><figure className="overflow-hidden rounded-[16px] border border-neutral-200 bg-white"><img src={abmResourceImagePath("https://www.abmgood.com/assets/images/tinymce/YTWT2BgpvcBCZ4Hat9TlMgKeXiEszJUIIfewYmAl.png")} alt="Cardiomyocyte voltage-gated currents" className="h-auto w-full object-contain" /><figcaption className="p-4 text-[12px] font-semibold text-neutral-700">Electrophysiology · Voltage-Gated Currents</figcaption></figure><figure className="overflow-hidden rounded-[16px] border border-neutral-200 bg-white"><img src={abmResourceImagePath("https://www.abmgood.com/assets/images/tinymce/PC0NACDuJDfnOUJvTlahPvpdINtrVhy28mmIPKXg.png")} alt="Cardiomyocyte action potential response" className="h-auto w-full object-contain" /><figcaption className="p-4 text-[12px] font-semibold text-neutral-700">Electrophysiology · Action Potential Response</figcaption></figure></div></section>

    <section className="mt-6 rounded-[22px] border border-[#eadfd9] bg-white p-7"><SectionTitle eyebrow="TM213 Differentiation Medium Kit" title="Generate Functional Cardiomyocytes In-House" text="For researchers who want control over differentiation, TM213 supports a streamlined workflow for generating cardiomyocytes from human embryonic stem cells." /><div className="mt-5 overflow-hidden rounded-[16px] border border-neutral-200 bg-[#fafafa] p-4"><img src={abmResourceImagePath("https://www.abmgood.com/assets/images/tinymce/Yehoh2YWZdgqUggkBqP5fKIzP18XLpzpBzyktr1e.jpg")} alt="Human cardiomyocyte differentiation roadmap" className="mx-auto h-auto max-h-[480px] w-full object-contain" /></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><SmallCard title="Maintain Control" text="Run the differentiation workflow in your own laboratory." /><SmallCard title="Scale to Your Needs" text="Generate cells based on project demand." /><SmallCard title="Reproducible Protocol" text="Use an optimized workflow designed for consistent differentiation." /><SmallCard title="Compatible Platform" text="Integrate with toxicity, disease modelling, and 3D culture workflows." /></div></section>

    <section className="mt-6 rounded-[22px] border border-[#f0d2c5] bg-[#fff7f2] p-7"><div className="text-[11px] font-bold uppercase tracking-[0.12em] text-[#f15a29]">Promotional Cardiac Research Bundle</div><h2 className="mt-2 text-[25px] font-semibold text-[#414b55]">T5004 + 3DCelMatrix™ + Maintenance Medium Kit</h2><p className="mt-3 text-[13px] leading-6 text-neutral-700">A bundled cardiac workflow combines ready-to-use cardiomyocytes, extracellular-matrix support, and maintenance medium.</p></section>

    <section className="mt-6 rounded-[22px] border border-[#eadfd9] bg-white p-7"><SectionTitle eyebrow="FAQ" title="Frequently Asked Questions" /><div className="mt-5 space-y-3"><SmallCard title="How quickly do the cardiomyocytes begin beating?" text="Spontaneous contractions are typically observed within 3–5 days after plating." /><SmallCard title="What validation is performed?" text="Cardiac identity is evaluated using molecular markers, immunocytochemistry, electrophysiology, sterility, and post-thaw viability checks." /><SmallCard title="How long are the cells functionally stable?" text="Functional performance is typically maintained for approximately 10–14 days in culture." /></div></section>
  </CellLibraryShell>;
}
