import Link from "next/link";

import { CellLibraryShell } from "../../_cellLibraryShared";

export default function GranulocytesPage() {
  return <CellLibraryShell title="Granulocytes (Neutrophils, Eosinophils, Basophils)" active="hematopoietic-cells" subActive="granulocytes">
    <section className="border-b border-neutral-200 pb-8"><h1 className="text-[29px] font-semibold tracking-[-0.025em] text-[#414b55]">Granulocytes (Neutrophils, Eosinophils, Basophils)</h1><h2 className="mt-3 text-[20px] font-semibold text-[#414b55]">Human Granulocytes – Neutrophils, Eosinophils, and Basophils</h2><p className="mt-4 max-w-4xl text-[13px] leading-6 text-neutral-700">Freshly isolated or cryopreserved human granulocytes from peripheral blood provide research-ready innate-immune models for inflammation, allergen response, chemotaxis, cytokine profiling, and co-culture studies.</p><ul className="mt-5 list-disc space-y-2 pl-5 text-[13px] leading-5 text-neutral-700"><li><strong>Neutrophils:</strong> ≥95% purity, CD15⁺/CD16⁺ validated.</li><li><strong>Eosinophils:</strong> ≥95% purity, validated using Siglec-8⁺ and CCR3⁺ expression.</li><li><strong>Basophils:</strong> ≥90% purity, validated using FcεRI⁺/CD123⁺/CD203c⁺ markers.</li></ul></section>
    <section className="mt-7"><h2 className="text-[22px] font-semibold text-[#414b55]">Product List</h2><div className="mt-4 overflow-hidden rounded-md border border-neutral-200"><table className="w-full text-left text-[13px]"><thead><tr className="bg-neutral-50"><th className="px-4 py-3">Product Name</th><th className="px-4 py-3">Cat. No.</th><th className="px-4 py-3">Unit</th></tr></thead><tbody>{[["Neutrophils","T4187","2×10⁶ cells / 1.0 ml"],["Eosinophils","T4188","2×10⁶ cells / 1.0 ml"],["Basophils","T4189","2×10⁶ cells / 1.0 ml"]].map(([name,sku,unit]) => <tr key={sku} className="border-t border-neutral-200"><td className="px-4 py-3"><Link href={`/products/abm/staged/product/${sku}`} className="font-semibold text-[#d95628]">{name}</Link></td><td className="px-4 py-3">{sku}</td><td className="px-4 py-3">{unit}</td></tr>)}</tbody></table></div></section>
  </CellLibraryShell>;
}
