import Link from "next/link";

import AbmStagedCatalog from "@/components/products/AbmStagedCatalog";
import { abmRecordBelongsToProductPath } from "@/lib/abm/catalog-taxonomy";
import { getAbmStagedRecords } from "@/lib/abm/rebuild-staging";
import { CellLibraryShell, SearchBox, SectionTitle, SmallCard, Stat } from "../_cellLibraryShared";

export default async function StemCellDerivedCellsPage({ searchParams }: { searchParams?: Promise<{ q?: string; page?: string }> | { q?: string; page?: string } }) {
  const sp = await Promise.resolve(searchParams as any);
  const query = String(sp?.q || "").trim();
  const page = Math.max(1, Number.parseInt(String(sp?.page || "1"), 10) || 1);
  const all = await getAbmStagedRecords("product");
  const records = all.filter((record) => abmRecordBelongsToProductPath(record, ["cellular-materials", "cell-library-collections", "stem-cell-derived-cells"], "Stem Cell-Derived Cells"));

  return <CellLibraryShell title="Stem Cell-Derived Cells" active="stem-cell-derived-cells">
    <section className="rounded-[22px] border border-[#eadfd9] bg-[#fffaf7] p-7 md:p-8"><div className="text-[11px] font-bold uppercase tracking-[0.12em] text-[#f15a29]">Stem Cell-Derived Cells</div><h1 className="mt-2 text-[36px] font-semibold tracking-[-0.04em] text-[#414b55]">Cells Built for Discovery</h1><p className="mt-3 max-w-4xl text-[14px] leading-6 text-neutral-700">Lineage-committed cell models provide functional phenotype, defined genetics, and repeatable performance for disease modelling and screening workflows.</p><div className="mt-5 flex flex-wrap gap-2"><Link href="#research-systems" className="rounded-full bg-[#f15a29] px-5 py-2.5 text-[12px] font-bold text-white">Explore Models</Link><Link href="#stem-basics" className="rounded-full border border-[#f15a29] bg-white px-5 py-2.5 text-[12px] font-semibold text-[#f15a29]">Compare Cell Models</Link></div></section>

    <section className="mt-4 grid gap-3 md:grid-cols-3"><Stat value="Functional" label="Phenotype" /><Stat value="Defined" label="Genetic consistency" /><Stat value="Repeatable" label="Lot-to-lot performance" /></section>

    <section id="research-systems" className="mt-6 rounded-[22px] border border-[#eadfd9] bg-white p-7"><SectionTitle eyebrow="Explore by research system" title="Select the organ system most relevant to your research" /><div className="mt-5 grid gap-5 md:grid-cols-2"><Link href="/products/abm/cellular-materials/cell-library-collections/stem-cell-derived-cells/neurological" className="group overflow-hidden rounded-[18px] border border-neutral-200 bg-white"><div className="aspect-[16/8] overflow-hidden bg-neutral-50"><img src="https://www.abmgood.com/assets/images/tinymce/ghcrHhKf0PaQn8I4dPbKYsKF2plCd9lO6Cl3L2nn.png" alt="Neurological system cells" className="h-full w-full object-cover transition group-hover:scale-[1.02]" /></div><div className="p-5"><div className="text-[11px] font-bold uppercase tracking-[0.1em] text-[#f15a29]">Neurological System</div><h3 className="mt-2 text-xl font-semibold">Neurological System</h3><p className="mt-2 text-[12px] leading-5 text-neutral-600">Neuronal and glial models for CNS disease research, neuropharmacology, and electrophysiology.</p></div></Link><Link href="/products/abm/cellular-materials/cell-library-collections/stem-cell-derived-cells/cardiovascular" className="group overflow-hidden rounded-[18px] border border-neutral-200 bg-white"><div className="aspect-[16/8] overflow-hidden bg-neutral-50"><img src="https://www.abmgood.com/assets/images/tinymce/eImxiMplCsIyx7DKOPo4H3lqNdgoeo49jOExac53.jpg" alt="Cardiovascular system cells" className="h-full w-full object-cover transition group-hover:scale-[1.02]" /></div><div className="p-5"><div className="text-[11px] font-bold uppercase tracking-[0.1em] text-[#f15a29]">Cardiovascular System</div><h3 className="mt-2 text-xl font-semibold">Cardiovascular System</h3><p className="mt-2 text-[12px] leading-5 text-neutral-600">Human cardiomyocyte models for cardiotoxicity, physiology, and cardiac disease modelling.</p></div></Link></div></section>

    <section className="mt-6 rounded-[22px] border border-[#eadfd9] bg-[#fffaf7] p-7"><SectionTitle eyebrow="Applications" title="Research-ready models for discovery workflows" /><div className="mt-4 flex flex-wrap gap-2">{["Disease Modelling", "Drug Screening & Toxicology", "Gene Editing & CRISPR", "Mechanistic Studies", "Cell Therapy Development", "Tissue Engineering", "Biomarker Discovery"].map((x) => <span key={x} className="rounded-full border border-[#ecd7ce] bg-white px-3 py-1.5 text-[11px] font-medium text-neutral-700">{x}</span>)}</div></section>

    <section id="stem-basics" className="mt-6 rounded-[22px] border border-[#eadfd9] bg-white p-7"><SectionTitle eyebrow="What are stem cell-derived cells?" title="Specialised cell models generated through directed differentiation" /><div className="mt-5 grid gap-4 md:grid-cols-3"><SmallCard title="iPSC-Derived" text="Donor somatic cells are reprogrammed to pluripotency and differentiated into a target lineage." /><SmallCard title="ESC-Derived" text="Embryonic stem cells provide a well-characterized pluripotent source for controlled differentiation." /><SmallCard title="Tissue Progenitor-Derived" text="Lineage-restricted progenitors can reduce heterogeneity and shorten differentiation workflows." /></div><div className="mt-5 overflow-hidden rounded-[16px] border border-neutral-200 bg-[#fafafa] p-4"><img src="https://www.abmgood.com/assets/images/tinymce/o4VQqsDhGU3uStg826b3vjYsaiHoYqDH4VYX8sQC.png" alt="Stem cell differentiation workflow" className="mx-auto h-auto max-h-[390px] w-full object-contain" /></div></section>

    <SearchBox title="Search stem cell-derived models" placeholder="Cell type, model, or catalog number…" />
    <AbmStagedCatalog kind="product" records={records} query={query} page={page} basePath="/products/abm/cellular-materials/cell-library-collections/stem-cell-derived-cells" />
  </CellLibraryShell>;
}
